# orbit.conf - Configurações do Orbit
# Edite este arquivo para personalizar host, porta e montagem

# Montagem remota
ORBIT_MOUNT_POINT="/home/d3xt4rz/Projects/MyVPS"
ORBIT_REMOTE="root@190.50.241.126:/root/Home"
ORBIT_PORT=22

# Conexão SSH
ORBIT_SSH_HOST="190.50.241.126"
ORBIT_SSH_PORT=22
ORBIT_SSH_USER="root"